server {
  listen 80;
  server_name 127.0.0.1;

  location /_AMapService/v4/map/styles {
    set $args "$args&jscode=89a3e2583feec1c50c910b5e8518451e";
    proxy_pass https://webapi.amap.com/v4/map/styles;
  }

  location /_AMapService/ {
    set $args "$args&jscode=89a3e2583feec1c50c910b5e8518451e";
    proxy_pass https://restapi.amap.com/;
  }
}
